---

# ОБЯЗАТЕЛЬНЫЕ ПЕРЕМЕННЫЕ ДЛЯ КАЖДОЙ ИЗ ВИРТУАЛЬНЫХ МАШИН:
#   setup                 - доступные переменные: true, false
#   name                  - name (имя виртуальной машины)
#   box_check_update      - проверка репозитория на наличие обновлений
#   keys_only: false      - можно подключаться по паролю
#   insert_key: false     - отменить создание ssh-ключа
#   ip_private            -
#   ip_public             -
#   ip_bridge             -
#   apache_document_root  - 

# ДИНАМИЧЕСКИЕ ПОРТЫ:
#   Диапазон 49152—65535 содержит динамически выделяемые или частные порты, которые не регистрируются IANA.
#   Эти порты используются временными (короткоживущими) соединениями «клиент — сервер» или в определенных частных случаях.
#     port_guest                - 
#     port_host                 - 50101 - 50999
#     port_ssh                  - 51101 - 51999
#     port_web_based_interface  - 52101 - 52999

# ДОПОЛНИТЕЛЬНЫЕ ПЕРЕМЕННЫЕ:
#   document_root         -
#   memory                - объем оперативной памяти, по умолчанию, если не указано, выделяется 1024Mb
#   cpu                   - количество ядер процессора, по умолчанию, если не указано, выделяется одно
#   mysql_dbname          - основная база данных сервера разработки приложений
#   
#   по умолчанию устанавливается образ системы, определённый в глобальных переменных
#   если необходима специфичность, определите для виртуальной машины следующие переменные:
#     box                   - образ системы
#     box_version           -

nodes:
  -
    # 
    description: "Локальный сервер репозитория APT"
    #   обязательные переменные:
    name: "local-apt"
    setup: true
    web_based_interface: "false"
    domain_prefix: "apt.meropa"
    box_check_update: false
    keys_only: false
    insert_key: false
    port_guest: 80
    port_host: 50101
    port_ssh: 51101
    port_web_based_interface: 52101
    ip_private: 10.255.0.101
    ip_public: 10.23.1.100
    #   дополнительные переменные:
    disksize: 512000MB
  
...