version: '3'

services:
  nginx:
    image: nginx:latest	
    container_name: nginx-balancer
    restart:
      always
    ports:
      - 80:80
    volumes:
      - ./nodes/config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      meropa:

networks:
  meropa:
    external:
      true