version: '3'

services:
  apache:
    image: httpd:2.4
    container_name: otus-lesson-12-hw-apache
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/local/apache2/htdocs
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:latest	
    container_name: otus-lesson-12-hw-nginx
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default:/etc/nginx/sites-available/default:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apache

  php:  
    container_name: otus-lesson-12-hw-php
    build:
      ./php
    volumes:
      - ./src:/usr/local/apache2/htdocs
      - ./php/php.ini:/usr/local/etc/php/php.ini
   