version: '3'

services:
  apache:
    image: httpd:2.4
    container_name: lesson-12-hw-apache
    expose:
      - 80
    volumes:
      - ./data-www:/usr/local/apache2/htdocs
      - ./nodes/config/apache/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:latest	
    container_name: lesson-12-hw-nginx
    ports:
      - 8080:80
    volumes:
      - ./data-www:/var/www/html
      - ./nodes/config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - apache

  php:
    image: php:8.0-fpm  
    container_name: lesson-12-hw-php
    volumes:
      - ./data-www:/usr/local/apache2/htdocs

  mysql_master:
    image: mysql:8.0.19
    container_name: lesson-12-hw-mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: master-secret-pw
    # административные права для root
    privileged: true
    volumes:
      - ./data-backup/mysql-master/data:/var/lib/mysql
      - ./nodes/config/mysql-master/mysql/:/etc/mysql/

  phpmyadmin_master:
    image: phpmyadmin/phpmyadmin:5.0.2  
    container_name: lesson-12-hw-pma-master
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_master
    depends_on:
      - mysql_master

  mysql_slave:
    image: mysql:8.0.19
    container_name: lesson-12-hw-mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: slave-secret-pw
    # административные права для root
    privileged: true
    volumes:
      - ./data-backup/mysql-slave/data:/var/lib/mysql
      - ./nodes/config/mysql-slave/mysql/:/etc/mysql/

  phpmyadmin_slave:
    image: phpmyadmin/phpmyadmin:5.0.2  
    container_name: lesson-12-hw-pma-slave
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql_slave
    depends_on:
      - mysql_slave
   