version: '3'

services:
  apache:
    image: httpd:2.4
    container_name: lesson-12-hw-apache
    expose:
      - 80
    volumes:
      - ./src:/usr/local/apache2/htdocs
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:latest	
    container_name: lesson-12-hw-nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - apache

  php:  
    container_name: lesson-12-hw-php
    image: php:8.0-fpm
    volumes:
      - ./src:/usr/local/apache2/htdocs
      - ./php/php.ini:/usr/local/etc/php/php.ini
   