version: '3'

services:

  nginx_unicom_primary:
    image: nginx:latest	
    container_name: nginx-unicom-primary
    expose:
      - 80
    volumes:
      - ./nodes/config/nginx-unicom-primary/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - apache_unicom_primary
    networks:
      meropa:

  apache_unicom_primary:
    image: httpd:2.4
    container_name: apache-unicom-primary
    expose:
      - 80
    volumes:
      - ./nodes/config/apache-unicom-primary/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php_unicom
    networks:
      meropa:

  php_unicom:
    image: php:8.0-fpm  
    container_name: php-unicom
    volumes:
      - ./data-www:/usr/local/apache2/htdocs
    networks:
      meropa:

networks:
  meropa:
    external:
      true
    