version: '3'

services:

  mysql_master:
    image: mysql:8.0.19
    container_name: lesson-12-hw-mysql-master
    restart:
      always
    environment:
      MYSQL_ROOT_PASSWORD: master-secret-pw
    # административные права для root
    privileged: true
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./nodes/config/mysql-master/mysql/:/etc/mysql/
      - ./nodes/config/mysql-master/mysql-files:/var/lib/mysql-files
    networks:
      meropa:

  phpmyadmin_master:
    image: phpmyadmin/phpmyadmin:5.0.2  
    container_name: lesson-12-hw-pma-master
    ports:
      - 8091:80
    environment:
      PMA_HOST: mysql_master
    depends_on:
      - mysql_master
    networks:
      meropa:

  mysql_slave:
    image: mysql:8.0.19
    container_name: lesson-12-hw-mysql-slave
    restart:
      always
    environment:
      MYSQL_ROOT_PASSWORD: slave-secret-pw
    # административные права для root
    privileged: true
    volumes:
      - mysql-slave-data:/var/lib/mysql
      - ./nodes/config/mysql-slave/mysql/:/etc/mysql/
      - ./nodes/config/mysql-slave/mysql-files:/var/lib/mysql-files
    networks:
      meropa:

  phpmyadmin_slave:
    image: phpmyadmin/phpmyadmin:5.0.2  
    container_name: lesson-12-hw-pma-slave
    ports:
      - 8092:80
    environment:
      PMA_HOST: mysql_slave
    depends_on:
      - mysql_slave
    networks:
      meropa:
   
volumes:
  mysql-master-data:
  mysql-slave-data:

networks:
  meropa:
    external:
      true
    