#!/bin/bash

destination="/backup/mysql-dump"
userDB="root"
passwordDB="FpTzLgIBC1Rtvi9f"
date=`date +%Y-%m-%d`
fulldate=`date +%Y-%m-%d-%H-%M-%S`
 
find $destination -type d \( -name "*-1[^5]" -o -name "*-[023]?" \) -mtime +30 -exec rm -R {} \; 2>&1
find $destination -type d -name "*-*" -mtime +180 -exec rm -R {} \; 2>&1
test -d $destination/$date || mkdir $destination/$date 2>&1
 
/usr/bin/mysqldump -u$userDB -p$passwordDB --all-databases | gzip > $destination/$date/all-databases-$fulldate.sql.gz